apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-scraper
  namespace: envoy
  labels:
    app: envoy-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-scraper
  template:
    metadata:
      labels:
        app: envoy-scraper
    spec:
      containers:
      - name: envoy-scraper
        image: docker.flame.org/library/envoy-scraper
        imagePullPolicy: Always
        env:
          - name: ENVOY_HOST
            value: "10.44.100.1"
          - name: ENVOY_SERIAL
            value: "123456789012"
          - name: ENVOY_SITE_ID
            value: "1234"
          - name: ENVOY_TOKEN
            value: "..." # should likely be in a secret
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://collector-agent.cardinalhq.svc.cluster.local:4317
        resources:
          requests:
            cpu: "100m"
            memory: "32Mi"
          limits:
            cpu: "500m"
            memory: "64Mi"
